
services:
  nextjs:
    build: .
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8083/api
    command: npm run dev -- -H 0.0.0.0
