import type {Metadata} from "next";
import "./globals.css";
import Sidebar from "@/app/my_components/SideBar";
import {Toaster} from "react-hot-toast";
import localFont from "next/font/local";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster position="top-right" containerClassName={"z-50"} toastOptions={{ duration: 5000 }} />

      <div className="flex h-screen">
          <Sidebar />
          <main className="flex-1 overflow-y-auto  flex flex-col gap-20 bg-gray-50">
              {children}
          </main>
      </div>
      </body>
    </html>
  );
}
