import type {Metadata} from "next";
import "./globals.css";
import {Toaster as SonnerToaster} from "@/components/ui/sonner";
import localFont from "next/font/local";
import {cn} from "@/lib/utils";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn("min-h-screen bg-background font-sans antialiased", geistSans.variable, geistMono.variable)}>
        <SonnerToaster richColors position="top-right"/>
        {children} {/* This is now controlled by sub-layouts */}
        </body>
        </html>
    );
}
